### ISSUE TITLE
MVPリリース　レビュー依頼

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#129]
MVPリリースレビュー依頼を作成させて頂きました。
ご確認の程よろしくお願い致します。
***

## 各種情報
**サービスの概要とMVPで検証する事柄：** 
本サービスは、カフェ好きのユーザー同士が自身のお気に入りのカフェを共有し合える投稿サービスです。ユーザーはカフェの情報を投稿し、他のユーザーと交流することで、新たなカフェの発見や交流を楽しむことができます。投稿には、カフェの雰囲気やメニュー、アクセス方法、営業時間などの詳細情報を写真付きで紹介できるため、他のユーザーが訪問を検討する際の参考として活用することが可能です。

また、ブックマーク機能を通じて、ユーザーは気に入った投稿や訪問予定のカフェを保存し、いつでも簡単に見返せます。このブックマーク機能により、ユーザーが個々の興味や訪問リストを管理しやすくなることが期待されています。

さらに、動的OGPに対応したX（旧Twitter）共有機能を実装しており、カフェの投稿をSNS上でシェアする際には、カード形式で情報が表示されます。これにより、サービス外でもユーザーが魅力的なカフェ情報を手軽に発信でき、他のユーザーが関心を持つきっかけが生まれます。

**サービス名：** Magco（マグコ）
**サービスURL：** https://magco.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [X] ログイン機能
- [X] 新規登録機能
- [X] ログアウト機能
- [X] リセットパスワード機能
- [X] 投稿一覧
- [X] 投稿詳細
- [X] 投稿作成
- [X] 投稿編集
- [X] 投稿削除
- [X] コメント作成
- [X] コメント編集
- [X] コメント削除
- [X] プロフィール詳細
- [X] プロフィール編集
- [X] ブックマーク機能
- [X] ブックマーク一覧
- [X] SNS共有機能（動的OGP）

## READMEレビュー時から変更した機能
機能ではありませんが、動的タイトルをファビコンを追加させて頂きました。

## サービスイメージがわかるようなスクリーンショット等
**[ログインページ]**
![スクリーンショット 2024-10-28 0 19 45](https://github.com/user-attachments/assets/e1ee3d60-71f7-4b01-9f1f-24518fb44f3e)

**[新規登録ページ]**
![スクリーンショット 2024-10-28 0 28 26](https://github.com/user-attachments/assets/02a33c1e-3421-4297-bb12-31a14b12c25e)

**[投稿一覧ページ]**
![スクリーンショット 2024-10-28 0 20 55](https://github.com/user-attachments/assets/816d2bf0-d80d-45de-8c17-d1f203db9563)

**[投稿詳細ページ]**
![スクリーンショット 2024-10-28 8 57 16](https://github.com/user-attachments/assets/9170e644-0fda-4bbb-a34b-6f9131a48137)
![スクリーンショット 2024-10-28 8 58 09](https://github.com/user-attachments/assets/201b1866-8847-4101-ac5d-1bbb195de2c0)

**[投稿作成ページ]**
![スクリーンショット 2024-10-29 9 06 16](https://github.com/user-attachments/assets/bfb25032-4b56-422d-bbc4-fd771751718f)

**[プロフィール詳細]**
![スクリーンショット 2024-10-29 9 03 42](https://github.com/user-attachments/assets/c32b29e8-e121-4fce-a534-fb10ef17d51b)

**[ブックマーク一覧ページ]**
![スクリーンショット 2024-10-28 9 07 38](https://github.com/user-attachments/assets/7636cf36-7e86-4233-b9e2-eaeaa43f4d5c)

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
