### ISSUE TITLE
”Issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by mayu0130** [mayu0130/Cafe-app#51]
■Webアプリの概要
カフェアプリ」は、コーヒーやスイーツが大好きなあなたのために設計された、カフェ体験を豊かにするためのプラットフォームです。

ユーザーは簡単にアカウントを作成し、お気に入りのカフェやスイーツを見つけて共有できます。
投稿一覧ページでは、他のユーザーが訪れたカフェのレビューやおすすめメニューをチェックでき、自分の体験を投稿することも可能です。
カフェの雰囲気やお店の内装、特に美味しかったメニューなどを記録に残し、自分のカフェ体験を共有することで、新たな発見が増えるでしょう。

さらに、おすすめのコーヒーやスイーツの情報を通して、あなたの次のお出かけ先を見つけることができます。
ブックマーク機能を活用すれば、行きたいカフェを簡単に保存でき、いつでもURLからアクセス可能。
ユーザのフォローフォロワー機能も備わっているので友達やお気に入りのカフェレビュアーをフォローすることで、最新の投稿やおすすめ情報を逃さずキャッチできます。
また診断機能が3種備わっているので自分のカフェスタイルやスイーツの好みを楽しみながら見つけることができます。

■1週間辺りの開発に向けられる時間
- 1週間あたり：30時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

■MVPリリースまで
- [ ] 環境構築
- [ ] トップページの表示（仮）
- [ ] lintツール rubocopの導入
- [ ] 共通ヘッダーの作成
- [ ] 共通フッターの作成
- [ ] 初期デプロイ
- [ ] 新規登録
- [ ] ログイン
- [ ] ログアウト
- [ ] 共通ヘッダーの修正（ログイン時・ログアウト時）
- [ ] パスワードリセット
- [ ] ユーザIDの作成
- [ ] 投稿一覧ページ
- [ ] 投稿詳細ページ
- [ ] 投稿作成ページ
- [ ] フラッシュメッセージの表示
- [ ] エラーメッセージの表示
- [ ] 日付の表記の変更
- [ ] 投稿編集ページ
- [ ] 投稿削除機能
- [ ] プロフィール詳細ページ
- [ ] プロフィール編集ページ
- [ ] 画像アップロード
- [ ] プロフィール詳細ページ（他ユーザ）
- [ ] ブックマーク一覧ページ
- [ ] ブックマーク機能
- [ ] お問い合わせ
- [ ] プライバシポリシー
- [ ] 利用規約
- [ ] SNS共有機能

■MVP後
- [ ] 検索機能
- [ ] オートコンプリート機能
- [ ] タグ機能
- [ ] フォロー機能
- [ ] アンフォロー機能
- [ ] フォロー一覧
- [ ] フォロワー一覧
- [ ] 診断一覧
- [ ] カフェドリンク診断機能
- [ ] コーヒー豆診断機能
- [ ] カフェデザート診断機能
- [ ] Goggle認証
- [ ] 投稿詳細ページに地図の表示
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年 11月 25日

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
以下気になった点のコメントになります。
***
- 11/11〜の週内で、ストーリーポイントが付いていないissueが見受けられました。
カリキュラムを確認して、適切にストーリーポイントを付与していただくようお願いします。
- ストーリーポイントについて、4ポイント以上のカードが見受けられました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化をお願いします。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。

上記コメント適用範囲は、MVPリリースまでの内容までで大丈夫です。
対応いただいたうえで、再度提出をお願いします。

**Comment by mayu0130** [comment]
コメントに沿って修正を行いましたので、ご確認をお願い致します。
***

> 11/11〜の週内で、ストーリーポイントが付いていないissueが見受けられました。
> カリキュラムを確認して、適切にストーリーポイントを付与していただくようお願いします。

- 申し訳ございません。11/11~のストーリポイントのついていないissueに追加させて頂きました。

***

> ストーリーポイントについて、4ポイント以上のカードが見受けられました。
> カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化をお願いします。細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。上記コメント適用範囲は、MVPリリースまでの内容までで大丈夫です。
> 

- MVPリリースまでのIssueにおいて4ポイント以上のものを3ポイント以下にしましたので、ご確認をお願いいたします。

### [修正点]
- **パスワードリセット 5ポイント→3ポイント**
カリキュラム外で2回deviseでパスワードリセットを行った経験があるので、ポイントを減らさせて頂きました。
- **SNS共有機能 8ポイント→3ポイント×2** 
こちらは初実装となるので、キャッチアップと実装でIssueを分けさせて頂きました。

**Comment by tarakish** [comment]
修正確認しました。LGTMです！
MVPリリースに向けて開発頑張ってください。
